import { useEffect, useState } from 'react'
import { CheckCircle2, Pencil, Search, X, XCircle } from 'lucide-react'
import { toast } from 'sonner'
import { useAuth } from '../../hooks/useAuth'
import { supabase } from '../../lib/supabase'
import type { Profile } from '../../types'
import { humanize } from '../../utils/format'

function roleLabel(profile: Profile) {
 if (profile.role === 'maintenance') return 'Technician'
 return profile.role === 'student' ? humanize(profile.account_type) : humanize(profile.role)
}

function filterRole(profile: Profile): 'student'|'teacher'|'staff'|'technician'|'admin' {
 if (profile.role === 'admin') return 'admin'
 if (profile.role === 'maintenance') return 'technician'
 return profile.account_type
}

export function UsersPage(){
 const{user:currentUser}=useAuth();const[users,setUsers]=useState<Profile[]>([]);const[query,setQuery]=useState('');const[systemRole,setSystemRole]=useState<'all'|'student'|'teacher'|'staff'|'technician'|'admin'>('all');const[editing,setEditing]=useState<Profile|null>(null);const[role,setRole]=useState<Profile['role']>('student');const[specialization,setSpecialization]=useState('');const[saving,setSaving]=useState(false)
 async function load(){const{data}=await supabase.from('profiles').select('*').order('created_at',{ascending:false});setUsers((data||[]) as Profile[])}
 useEffect(()=>{void load()},[])
 function edit(profile:Profile){setEditing(profile);setRole(profile.role);setSpecialization(profile.specialization||'')}
 function close(){setEditing(null);setSpecialization('')}
 async function verify(profile:Profile,decision:'approved'|'rejected'){setSaving(true);const{error}=await supabase.rpc('admin_verify_account',{target_user_id:profile.id,decision});setSaving(false);if(error)return toast.error('Verification failed. Apply the latest Supabase SQL update first.');toast.success(decision==='approved'?`${humanize(profile.account_type)} account approved.`:'Account registration rejected.');await load()}
 async function save(e:React.FormEvent){e.preventDefault();if(!editing)return;setSaving(true);const{error}=await supabase.rpc('admin_manage_user_role',{target_user_id:editing.id,new_role:role,new_specialization:specialization});setSaving(false);if(error)return toast.error('Could not update the user role.');toast.success(role==='maintenance'?'Technician role assigned. The staff member can now receive maintenance assignments.':'User role updated.');close();await load()}
 const shown=users.filter(u=>(systemRole==='all'||filterRole(u)===systemRole)&&`${u.full_name} ${u.email||''} ${u.student_id||''} ${u.specialization||''} ${u.department||''} ${u.account_type} ${roleLabel(u)}`.toLowerCase().includes(query.toLowerCase()))
 const pending=users.filter(u=>u.verification_status==='pending').length
 return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="display text-4xl">Users & staff</h1><p className="mt-2 text-slate-500">Verify teacher/staff identities and manage system roles.</p>{pending>0&&<p className="mt-2 inline-flex rounded-full bg-amber-100 px-3 py-1 text-sm font-semibold text-amber-800">{pending} account{pending===1?'':'s'} awaiting verification</p>}</div><div className="flex flex-wrap items-end gap-3"><label><span className="label">System role</span><select className="input min-w-40" value={systemRole} onChange={e=>setSystemRole(e.target.value as typeof systemRole)}><option value="all">All roles</option><option value="student">Students</option><option value="teacher">Teachers</option><option value="staff">Staff</option><option value="technician">Technicians</option><option value="admin">Administrators</option></select></label><label className="relative min-w-64"><span className="label">Search</span><Search className="absolute bottom-3 left-3 text-slate-400" size={18}/><input className="input pl-10" placeholder="Name, email, or ID" value={query} onChange={e=>setQuery(e.target.value)}/></label></div></div>
 <div className="card mt-7 overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase text-slate-400"><tr><th className="px-5 py-4">Name</th><th>Account type</th><th>ID / department</th><th>System role</th><th>Verification</th><th className="pr-5 text-right">Action</th></tr></thead><tbody>{shown.map(u=><tr className="border-b last:border-0" key={u.id}><td className="px-5 py-4"><b>{u.full_name}</b><small className="block text-slate-400">{u.email}</small></td><td>{humanize(u.account_type)}</td><td><span>{u.student_id||'—'}</span>{u.department&&<small className="block text-slate-400">{u.department}</small>}</td><td><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${u.role==='maintenance'?'bg-amber-100 text-amber-800':u.role==='admin'?'bg-forest-100 text-forest-800':u.account_type==='teacher'?'bg-blue-100 text-blue-700':'bg-slate-100 text-slate-700'}`}>{roleLabel(u)}</span></td><td><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${u.verification_status==='approved'?'bg-green-100 text-green-700':u.verification_status==='pending'?'bg-amber-100 text-amber-800':'bg-red-100 text-red-700'}`}>{humanize(u.verification_status)}</span></td><td className="pr-5"><div className="flex justify-end gap-2">{u.verification_status==='pending'&&<><button className="btn-primary px-3 py-2" disabled={saving} onClick={()=>verify(u,'approved')}><CheckCircle2 size={15}/>Approve</button><button className="btn-secondary px-3 py-2 text-red-700" disabled={saving} onClick={()=>verify(u,'rejected')}><XCircle size={15}/>Reject</button></>}<button className="btn-secondary px-3 py-2" disabled={u.id===currentUser?.id||u.verification_status!=='approved'} onClick={()=>edit(u)}><Pencil size={15}/>Manage role</button></div></td></tr>)}</tbody></table></div>
 {editing&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4" role="dialog" aria-modal="true" aria-labelledby="role-dialog-title"><form className="card w-full max-w-md p-6" onSubmit={save}><div className="flex items-start justify-between gap-4"><div><h2 id="role-dialog-title" className="text-lg font-bold">Manage user role</h2><p className="mt-1 text-sm text-slate-500">{editing.full_name} · {humanize(editing.account_type)}</p></div><button type="button" className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-100" onClick={close} aria-label="Close"><X size={19}/></button></div><label className="mt-5 block"><span className="label">System role</span><select className="input" value={role} onChange={e=>setRole(e.target.value as Profile['role'])}><option value="student">{humanize(editing.account_type)} portal / reporter</option>{editing.account_type==='staff'&&<option value="maintenance">Technician</option>}<option value="admin">Administrator</option></select></label>{role==='maintenance'&&<label className="mt-4 block"><span className="label">Technician specialization</span><input className="input" maxLength={100} placeholder="e.g. Electrical, Plumbing, General" value={specialization} onChange={e=>setSpecialization(e.target.value)}/></label>}<div className="mt-6 flex justify-end gap-3"><button type="button" className="btn-secondary" onClick={close}>Cancel</button><button className="btn-primary" disabled={saving}>{saving?'Saving…':'Save role'}</button></div></form></div>}
 </div>
}
